package tmux

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/nemke/nagare-go/internal/git"
	"github.com/nemke/nagare-go/internal/models"
)

// RawSession is a parsed tmux session from list-sessions.
type RawSession struct {
	Name      string
	SessionID string
	Path      string
}

// PaneInfo is a parsed agent pane from list-panes.
type PaneInfo struct {
	WindowIndex int
	PaneIndex   int
	AgentType   models.AgentType
	WindowName  string
	PaneID      string
	Path        string // pane_current_path — the pane's own cwd, which may be a worktree
}

var agentProcesses = map[string]models.AgentType{
	"claude":   models.AgentClaude,
	"opencode": models.AgentOpenCode,
	"pi":       models.AgentPi,
	"codex":    models.AgentCodex,
}

// ParseSessions parses tmux list-sessions output.
// Format: "#{session_name}:#{session_id}:#{session_path}"
func ParseSessions(raw string) []RawSession {
	var sessions []RawSession
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, ":", 3)
		if len(parts) != 3 {
			continue
		}
		sessions = append(sessions, RawSession{
			Name:      parts[0],
			SessionID: parts[1],
			Path:      parts[2],
		})
	}
	return sessions
}

// ParseAllPanes parses tmux list-panes -a output.
// Format: "#{session_name}:#{window_index}:#{pane_index}:#{pane_current_command}:#{pane_pid}:#{window_name}:#{pane_id}:#{pane_current_path}"
// Returns agent panes grouped by session name.
// Accepts 5- through 8-field input for backward compatibility.
func ParseAllPanes(raw string) map[string][]PaneInfo {
	result := make(map[string][]PaneInfo)
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, ":", 8)
		if len(parts) < 5 {
			continue
		}
		sessionName := parts[0]
		windowIdx, _ := strconv.Atoi(parts[1])
		paneIdx, _ := strconv.Atoi(parts[2])
		cmd := strings.TrimSpace(parts[3])
		pid := parts[4]
		windowName := ""
		if len(parts) >= 6 {
			windowName = strings.TrimSpace(parts[5])
		}
		paneID := ""
		if len(parts) >= 7 {
			paneID = strings.TrimSpace(parts[6])
		}
		panePath := ""
		if len(parts) >= 8 {
			panePath = strings.TrimSpace(parts[7])
		}

		agentType, ok := agentProcesses[cmd]
		if !ok {
			agentType, ok = resolveAgentFromDescendants(pid)
			if !ok {
				continue
			}
		}

		result[sessionName] = append(result[sessionName], PaneInfo{
			WindowIndex: windowIdx,
			PaneIndex:   paneIdx,
			AgentType:   agentType,
			WindowName:  windowName,
			PaneID:      paneID,
			Path:        panePath,
		})
	}
	return result
}

// descendantAgents maps process names found in /proc cmdline to agent types.
// pi appears here as well as in agentProcesses: the standalone binary shows up as
// pane_current_command, while the npm install runs as a node descendant.
var descendantAgents = map[string]models.AgentType{
	"gemini": models.AgentGemini,
	"crush":  models.AgentCrush,
	"pi":     models.AgentPi,
	"codex":  models.AgentCodex,
}

// resolveAgentFromDescendants walks the process tree via /proc to find
// known agents running as descendants (e.g. zsh → node → crush).
// Linux-only: silently returns false on macOS/other platforms.
func resolveAgentFromDescendants(pid string) (models.AgentType, bool) {
	// BFS through child processes, max 3 levels deep.
	queue := []string{pid}
	for depth := 0; depth < 3 && len(queue) > 0; depth++ {
		var next []string
		for _, p := range queue {
			childrenPath := fmt.Sprintf("/proc/%s/task/%s/children", p, p)
			data, err := os.ReadFile(childrenPath)
			if err != nil {
				continue
			}
			for _, childPid := range strings.Fields(string(data)) {
				next = append(next, childPid)
				cmdline, err := os.ReadFile(fmt.Sprintf("/proc/%s/cmdline", childPid))
				if err != nil {
					continue
				}
				for _, arg := range strings.Split(string(cmdline), "\x00") {
					base := arg
					if idx := strings.LastIndex(arg, "/"); idx >= 0 {
						base = arg[idx+1:]
					}
					if agentType, ok := descendantAgents[base]; ok {
						return agentType, true
					}
				}
			}
		}
		queue = next
	}
	return "", false
}

// autoWindowNames are window names set by tmux or shells, not by the user.
var autoWindowNames = map[string]bool{
	"zsh": true, "bash": true, "fish": true, "sh": true,
	"terminal": true,
}

// isCustomWindowName returns true if the window name was set by the user,
// not auto-generated by tmux (e.g. "? claude", "zsh", "terminal").
func isCustomWindowName(windowName, sessionName string) bool {
	if windowName == "" || windowName == sessionName {
		return false
	}
	if strings.HasPrefix(windowName, "? ") {
		return false
	}
	return !autoWindowNames[windowName]
}

// ComputeDisplayNames returns a map from pane_id to display name for a set of
// agent panes sharing a tmux session. worktreeOf maps pane_id to a worktree
// basename for panes sitting in a linked worktree, and may be nil.
//
// Name precedence, highest first: a window name the user set, the worktree the
// pane sits in, then "{agent}_NN" (1-based, per agent type, ordered by
// window/pane). A single pane outside a worktree keeps the bare session name.
func ComputeDisplayNames(sessName string, panes []PaneInfo, worktreeOf map[string]string) map[string]string {
	result := make(map[string]string, len(panes))
	if len(panes) == 1 && worktreeOf[panes[0].PaneID] == "" {
		result[panes[0].PaneID] = sessName
		return result
	}

	sorted := make([]PaneInfo, len(panes))
	copy(sorted, panes)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].WindowIndex != sorted[j].WindowIndex {
			return sorted[i].WindowIndex < sorted[j].WindowIndex
		}
		return sorted[i].PaneIndex < sorted[j].PaneIndex
	})

	// labelFor returns the pane's preferred name fragment, or "" when it has
	// none and must fall back to the numbered form.
	labelFor := func(p PaneInfo) string {
		if isCustomWindowName(p.WindowName, sessName) {
			return p.WindowName
		}
		return worktreeOf[p.PaneID]
	}

	// Count labels first so the numbered fallback only applies where a label
	// is actually shared by more than one pane.
	taken := make(map[string]int)
	for _, p := range sorted {
		if label := labelFor(p); label != "" {
			taken[label]++
		}
	}

	counts := make(map[models.AgentType]int)
	for _, p := range sorted {
		label := labelFor(p)
		if label != "" && taken[label] == 1 {
			result[p.PaneID] = sessName + "/" + label
			continue
		}
		counts[p.AgentType]++
		if label == "" {
			label = string(p.AgentType)
		}
		result[p.PaneID] = fmt.Sprintf("%s/%s_%02d", sessName, label, counts[p.AgentType])
	}
	return result
}

// hookStateMap maps hook state strings to SessionStatus.
var hookStateMap = map[string]models.SessionStatus{
	"working":       models.StatusRunning,
	"waiting_input": models.StatusWaitingInput,
	"idle":          models.StatusIdle,
	"dead":          models.StatusDead,
}

// ScanSessions discovers all agent sessions in tmux.
// paneStates should be pre-loaded via state.LoadStatesByPaneID() and
// cwdStates via state.LoadAllStates(). The scanner looks up hook state
// by pane_id first; if not found, falls back to the pane's own directory.
func ScanSessions(paneStates map[string]models.SessionState, cwdStates map[string]models.SessionState) []models.Session {
	rawSessions := RunTmux("list-sessions", "-F", "#{session_name}:#{session_id}:#{session_path}")
	sessions := ParseSessions(rawSessions)

	rawPanes := RunTmux("list-panes", "-a", "-F", "#{session_name}:#{window_index}:#{pane_index}:#{pane_current_command}:#{pane_pid}:#{window_name}:#{pane_id}:#{pane_current_path}")
	allPanes := ParseAllPanes(rawPanes)

	var result []models.Session
	repos := make(map[string]git.Repo) // one git call per unique directory per scan
	describe := func(dir string) git.Repo {
		if r, ok := repos[dir]; ok {
			return r
		}
		r := git.Describe(dir)
		repos[dir] = r
		return r
	}

	for _, sess := range sessions {
		panes, ok := allPanes[sess.Name]
		if !ok {
			continue
		}

		// A pane may sit in a worktree, so resolve its own directory before
		// naming it or looking up its state.
		panePaths := make(map[string]string, len(panes))
		worktreeOf := make(map[string]string, len(panes))
		for _, pane := range panes {
			path := pane.Path
			if path == "" {
				path = sess.Path
			}
			panePaths[pane.PaneID] = path
			if wt := describe(path).Worktree; wt != "" {
				worktreeOf[pane.PaneID] = wt
			}
		}

		displayNames := ComputeDisplayNames(sess.Name, panes, worktreeOf)
		for _, pane := range panes {
			path := panePaths[pane.PaneID]

			var hookState models.SessionState
			var hasHook bool
			if pane.PaneID != "" {
				hookState, hasHook = paneStates[pane.PaneID]
			}
			if !hasHook {
				hookState, hasHook = cwdStates[path]
			}

			var status models.SessionStatus
			var lastMessage string
			var details models.SessionDetails

			if hasHook {
				s, ok := hookStateMap[hookState.State]
				if ok {
					status = s
				} else {
					status = models.StatusIdle
				}
				lastMessage = hookState.LastMessage
				details.LastActivity = hookState.Timestamp
				details.LastEvent = hookState.Event
			} else {
				status = models.StatusIdle
			}

			// Git facts come from the pane's own directory, which for a
			// worktree pane is not the tmux session directory.
			repo := describe(path)
			details.GitBranch = repo.Branch
			details.Worktree = repo.Worktree
			details.RepoName = repo.RepoName

			result = append(result, models.Session{
				Name:        displayNames[pane.PaneID],
				SessionID:   sess.SessionID,
				SessionName: sess.Name,
				Path:        path,
				WindowIndex: pane.WindowIndex,
				PaneIndex:   pane.PaneIndex,
				PaneID:      pane.PaneID,
				Status:      status,
				AgentType:   pane.AgentType,
				Details:     details,
				LastMessage: lastMessage,
			})
		}
	}
	return result
}
