package tmux

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"

	"github.com/nemke/nagare-go/internal/models"
)

// RawSession is a parsed tmux session from list-sessions.
type RawSession struct {
	Name      string
	SessionID string
	Path      string
}

// PaneInfo is a parsed agent pane from list-panes.
type PaneInfo struct {
	WindowIndex int
	PaneIndex   int
	AgentType   models.AgentType
	WindowName  string
	PaneID      string
}

var agentProcesses = map[string]models.AgentType{
	"claude":   models.AgentClaude,
	"opencode": models.AgentOpenCode,
}

// ParseSessions parses tmux list-sessions output.
// Format: "#{session_name}:#{session_id}:#{session_path}"
func ParseSessions(raw string) []RawSession {
	var sessions []RawSession
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, ":", 3)
		if len(parts) != 3 {
			continue
		}
		sessions = append(sessions, RawSession{
			Name:      parts[0],
			SessionID: parts[1],
			Path:      parts[2],
		})
	}
	return sessions
}

// ParseAllPanes parses tmux list-panes -a output.
// Format: "#{session_name}:#{window_index}:#{pane_index}:#{pane_current_command}:#{pane_pid}:#{window_name}:#{pane_id}"
// Returns agent panes grouped by session name.
// Accepts 5-, 6-, or 7-field input for backward compatibility.
func ParseAllPanes(raw string) map[string][]PaneInfo {
	result := make(map[string][]PaneInfo)
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, ":", 7)
		if len(parts) < 5 {
			continue
		}
		sessionName := parts[0]
		windowIdx, _ := strconv.Atoi(parts[1])
		paneIdx, _ := strconv.Atoi(parts[2])
		cmd := strings.TrimSpace(parts[3])
		pid := parts[4]
		windowName := ""
		if len(parts) >= 6 {
			windowName = strings.TrimSpace(parts[5])
		}
		paneID := ""
		if len(parts) >= 7 {
			paneID = strings.TrimSpace(parts[6])
		}

		agentType, ok := agentProcesses[cmd]
		if !ok {
			agentType, ok = resolveAgentFromDescendants(pid)
			if !ok {
				continue
			}
		}

		result[sessionName] = append(result[sessionName], PaneInfo{
			WindowIndex: windowIdx,
			PaneIndex:   paneIdx,
			AgentType:   agentType,
			WindowName:  windowName,
			PaneID:      paneID,
		})
	}
	return result
}

// descendantAgents maps process names found in /proc cmdline to agent types.
var descendantAgents = map[string]models.AgentType{
	"gemini": models.AgentGemini,
	"crush":  models.AgentCrush,
}

// resolveAgentFromDescendants walks the process tree via /proc to find
// known agents running as descendants (e.g. zsh → node → crush).
// Linux-only: silently returns false on macOS/other platforms.
func resolveAgentFromDescendants(pid string) (models.AgentType, bool) {
	// BFS through child processes, max 3 levels deep.
	queue := []string{pid}
	for depth := 0; depth < 3 && len(queue) > 0; depth++ {
		var next []string
		for _, p := range queue {
			childrenPath := fmt.Sprintf("/proc/%s/task/%s/children", p, p)
			data, err := os.ReadFile(childrenPath)
			if err != nil {
				continue
			}
			for _, childPid := range strings.Fields(string(data)) {
				next = append(next, childPid)
				cmdline, err := os.ReadFile(fmt.Sprintf("/proc/%s/cmdline", childPid))
				if err != nil {
					continue
				}
				for _, arg := range strings.Split(string(cmdline), "\x00") {
					base := arg
					if idx := strings.LastIndex(arg, "/"); idx >= 0 {
						base = arg[idx+1:]
					}
					if agentType, ok := descendantAgents[base]; ok {
						return agentType, true
					}
				}
			}
		}
		queue = next
	}
	return "", false
}

// autoWindowNames are window names set by tmux or shells, not by the user.
var autoWindowNames = map[string]bool{
	"zsh": true, "bash": true, "fish": true, "sh": true,
	"terminal": true,
}

// isCustomWindowName returns true if the window name was set by the user,
// not auto-generated by tmux (e.g. "? claude", "zsh", "terminal").
func isCustomWindowName(windowName, sessionName string) bool {
	if windowName == "" || windowName == sessionName {
		return false
	}
	if strings.HasPrefix(windowName, "? ") {
		return false
	}
	return !autoWindowNames[windowName]
}

// ComputeDisplayNames returns a map from pane_id to display name for a set of
// agent panes sharing a tmux session. When there's only one pane, the bare
// session name is used. When multiple panes share the session, panes with a
// custom window name use "{sessName}/{windowName}" and the rest get
// "{sessName}/{agent}_NN" (1-based, per agent type, ordered by window/pane).
func ComputeDisplayNames(sessName string, panes []PaneInfo) map[string]string {
	result := make(map[string]string, len(panes))
	if len(panes) == 1 {
		result[panes[0].PaneID] = sessName
		return result
	}

	sorted := make([]PaneInfo, len(panes))
	copy(sorted, panes)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].WindowIndex != sorted[j].WindowIndex {
			return sorted[i].WindowIndex < sorted[j].WindowIndex
		}
		return sorted[i].PaneIndex < sorted[j].PaneIndex
	})

	counts := make(map[models.AgentType]int)
	for _, p := range sorted {
		if isCustomWindowName(p.WindowName, sessName) {
			result[p.PaneID] = sessName + "/" + p.WindowName
			continue
		}
		counts[p.AgentType]++
		result[p.PaneID] = fmt.Sprintf("%s/%s_%02d", sessName, p.AgentType, counts[p.AgentType])
	}
	return result
}

// gitBranch returns the current git branch for a directory, or "".
func gitBranch(dir string) string {
	cmd := exec.Command("git", "-C", dir, "branch", "--show-current")
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// hookStateMap maps hook state strings to SessionStatus.
var hookStateMap = map[string]models.SessionStatus{
	"working":       models.StatusRunning,
	"waiting_input": models.StatusWaitingInput,
	"idle":          models.StatusIdle,
	"dead":          models.StatusDead,
}

// ScanSessions discovers all agent sessions in tmux.
// paneStates should be pre-loaded via state.LoadStatesByPaneID() and
// cwdStates via state.LoadAllStates(). The scanner looks up hook state
// by pane_id first; if not found, falls back to cwd.
func ScanSessions(paneStates map[string]models.SessionState, cwdStates map[string]models.SessionState) []models.Session {
	rawSessions := RunTmux("list-sessions", "-F", "#{session_name}:#{session_id}:#{session_path}")
	sessions := ParseSessions(rawSessions)

	rawPanes := RunTmux("list-panes", "-a", "-F", "#{session_name}:#{window_index}:#{pane_index}:#{pane_current_command}:#{pane_pid}:#{window_name}:#{pane_id}")
	allPanes := ParseAllPanes(rawPanes)

	var result []models.Session
	for _, sess := range sessions {
		panes, ok := allPanes[sess.Name]
		if !ok {
			continue
		}
		displayNames := ComputeDisplayNames(sess.Name, panes)
		for _, pane := range panes {
			var hookState models.SessionState
			var hasHook bool
			if pane.PaneID != "" {
				hookState, hasHook = paneStates[pane.PaneID]
			}
			if !hasHook {
				hookState, hasHook = cwdStates[sess.Path]
			}

			var status models.SessionStatus
			var lastMessage string
			var details models.SessionDetails

			if hasHook {
				s, ok := hookStateMap[hookState.State]
				if ok {
					status = s
				} else {
					status = models.StatusIdle
				}
				lastMessage = hookState.LastMessage
				details.LastActivity = hookState.Timestamp
				details.LastEvent = hookState.Event
			} else {
				status = models.StatusIdle
			}

			// Get git branch from working directory
			details.GitBranch = gitBranch(sess.Path)

			result = append(result, models.Session{
				Name:        displayNames[pane.PaneID],
				SessionID:   sess.SessionID,
				SessionName: sess.Name,
				Path:        sess.Path,
				WindowIndex: pane.WindowIndex,
				PaneIndex:   pane.PaneIndex,
				PaneID:      pane.PaneID,
				Status:      status,
				AgentType:   pane.AgentType,
				Details:     details,
				LastMessage: lastMessage,
			})
		}
	}
	return result
}
